import { describe, it, expect } from 'vitest'
import {
  buildRecipeMetadata,
  buildRecipeJsonLd,
  serializeJsonLd,
  type RecipeSeoInput,
} from '@/domain/recipe-seo'

/**
 * Builders PUROS de SEO do detalhe da Receita (#232 OG, #233 canonical/hreflang/robots, #234
 * JSON-LD) — sem DB, sem React, sem `next/*`. Recebem os dados JÁ carregados/resolvidos (nome,
 * corpo, slugs por locale, imagem, proveniência) e a `baseUrl` build-safe (env, sem `headers()`),
 * e devolvem o objeto `Metadata` do Next (#232/#233) e o objeto JSON-LD `schema.org/Recipe` (#234).
 * O `generateMetadata` e a página viram cascas finas que carregam o I/O e chamam estes builders.
 *
 * Decisões travadas exercitadas aqui:
 *  - OG sem selo de IA mesmo com imagem `ai_generated` (no card a imagem é vitrine — #232).
 *  - canonical = slug do locale CORRENTE; hreflang SÓ pros locales que TÊM tradução pública com
 *    slug + x-default → DEFAULT_LOCALE (#233). NÃO inventa URL de locale inexistente.
 *  - robots index/follow pra elegível; noindex pra não-elegível (#233).
 *  - JSON-LD sem `aggregateRating`/estrelas; ingredientes/passos/imagem/inLanguage (#234).
 */

const BASE = 'https://refogando.com'

// Fixture-base de uma Receita pública pt-BR com tradução en-US (ambos com slug).
function baseInput(over: Partial<RecipeSeoInput> = {}): RecipeSeoInput {
  return {
    locale: 'pt-BR',
    baseUrl: BASE,
    name: 'Bolo de Cenoura',
    description: 'Um bolo fofinho de cenoura com cobertura de chocolate.',
    ingredients: ['2 cenouras médias', '3 ovos', '2 xícaras de farinha'],
    steps: ['Bata os líquidos.', 'Misture os secos.', 'Asse por 40 minutos.'],
    slugsByLocale: { 'pt-BR': 'bolo-de-cenoura', 'en-US': 'carrot-cake' },
    brandName: 'Refogando',
    ...over,
  }
}

describe('buildRecipeMetadata — OG (#232)', () => {
  it('emite og:title/description/url/type + twitter summary_large_image', () => {
    const meta = buildRecipeMetadata(baseInput())
    expect(meta.openGraph?.title).toBe('Bolo de Cenoura')
    expect(meta.openGraph?.description).toBe(
      'Um bolo fofinho de cenoura com cobertura de chocolate.',
    )
    // `type`/`card` vivem em membros específicos da união OpenGraph/Twitter — narrow por `in`.
    const og = meta.openGraph
    expect(og && 'type' in og ? og.type : undefined).toBe('article')
    expect(meta.openGraph?.url).toBe(`${BASE}/pt-BR/recipes/bolo-de-cenoura`)
    const tw = meta.twitter
    expect(tw && 'card' in tw ? tw.card : undefined).toBe('summary_large_image')
  })

  it('usa a FOTO da receita como og:image quando há imageUrl (URL absoluta)', () => {
    const url = 'https://abc.public.blob.vercel-storage.com/recipes/x.webp'
    const meta = buildRecipeMetadata(baseInput({ imageUrl: url }))
    const images = meta.openGraph?.images
    const first = Array.isArray(images) ? images[0] : images
    const got = typeof first === 'object' && first != null && 'url' in first ? first.url : first
    expect(got).toBe(url)
  })

  it('cai no card de MARCA (asset default estável) quando NÃO há imagem', () => {
    const meta = buildRecipeMetadata(baseInput({ imageUrl: undefined }))
    const images = meta.openGraph?.images
    const first = Array.isArray(images) ? images[0] : images
    const got = typeof first === 'object' && first != null && 'url' in first ? first.url : first
    // Asset absoluto sob a baseUrl (não um path relativo nu).
    expect(String(got)).toBe(`${BASE}/opengraph-image.png`)
  })

  it('NÃO leva selo de IA no OG mesmo com imagem ai_generated (a imagem é vitrine)', () => {
    const url = 'https://abc.public.blob.vercel-storage.com/recipes/ai.webp'
    const meta = buildRecipeMetadata(baseInput({ imageUrl: url, imageAiGenerated: true }))
    const blob = JSON.stringify(meta)
    // Nenhuma menção a "IA"/"AI"/"gerada" nas tags OG/twitter (title/description vêm do conteúdo).
    expect(blob).not.toMatch(/gerada por IA|generated by AI|✨/i)
  })

  it('metadataBase é a baseUrl build-safe (env), nunca derivada de headers()', () => {
    const meta = buildRecipeMetadata(baseInput())
    expect(meta.metadataBase?.toString()).toBe(`${BASE}/`)
  })
})

describe('buildRecipeMetadata — canonical + hreflang + x-default + robots (#233)', () => {
  it('canonical aponta pro slug do locale CORRENTE', () => {
    const meta = buildRecipeMetadata(baseInput({ locale: 'pt-BR' }))
    expect(meta.alternates?.canonical).toBe(`${BASE}/pt-BR/recipes/bolo-de-cenoura`)
    const metaEn = buildRecipeMetadata(baseInput({ locale: 'en-US' }))
    expect(metaEn.alternates?.canonical).toBe(`${BASE}/en-US/recipes/carrot-cake`)
  })

  it('hreflang inclui APENAS os locales com slug público + x-default → DEFAULT_LOCALE', () => {
    const meta = buildRecipeMetadata(baseInput())
    const langs = meta.alternates?.languages ?? {}
    expect(langs['pt-BR']).toBe(`${BASE}/pt-BR/recipes/bolo-de-cenoura`)
    expect(langs['en-US']).toBe(`${BASE}/en-US/recipes/carrot-cake`)
    // x-default aponta pro DEFAULT_LOCALE (pt-BR).
    expect(langs['x-default']).toBe(`${BASE}/pt-BR/recipes/bolo-de-cenoura`)
  })

  it('NÃO inventa hreflang de locale sem tradução pública (acervo só pt-BR hoje)', () => {
    const meta = buildRecipeMetadata(
      baseInput({ slugsByLocale: { 'pt-BR': 'so-portugues' } }),
    )
    const langs = meta.alternates?.languages ?? {}
    expect(langs['pt-BR']).toBe(`${BASE}/pt-BR/recipes/so-portugues`)
    expect(langs['en-US']).toBeUndefined()
    // x-default cai no DEFAULT_LOCALE existente.
    expect(langs['x-default']).toBe(`${BASE}/pt-BR/recipes/so-portugues`)
  })

  it('robots = index/follow pra Receita pública elegível (eligible !== false)', () => {
    const meta = buildRecipeMetadata(baseInput({ eligible: true }))
    const robots = meta.robots
    const r = typeof robots === 'object' && robots != null ? robots : {}
    expect(r.index).toBe(true)
    expect(r.follow).toBe(true)
  })

  it('robots = noindex quando NÃO elegível (caminho do dono/privado/não-público)', () => {
    const meta = buildRecipeMetadata(baseInput({ eligible: false }))
    const robots = meta.robots
    const r = typeof robots === 'object' && robots != null ? robots : {}
    expect(r.index).toBe(false)
  })
})

describe('buildRecipeJsonLd — schema.org/Recipe (#234)', () => {
  it('emite Recipe com name/description/ingredientes/passos(HowToStep)/inLanguage', () => {
    const ld = buildRecipeJsonLd(baseInput())
    expect(ld['@context']).toBe('https://schema.org')
    expect(ld['@type']).toBe('Recipe')
    expect(ld.name).toBe('Bolo de Cenoura')
    expect(ld.description).toBe('Um bolo fofinho de cenoura com cobertura de chocolate.')
    expect(ld.inLanguage).toBe('pt-BR')
    expect(ld.recipeIngredient).toEqual([
      '2 cenouras médias',
      '3 ovos',
      '2 xícaras de farinha',
    ])
    expect(ld.recipeInstructions).toEqual([
      { '@type': 'HowToStep', text: 'Bata os líquidos.' },
      { '@type': 'HowToStep', text: 'Misture os secos.' },
      { '@type': 'HowToStep', text: 'Asse por 40 minutos.' },
    ])
  })

  it('image = a foto VISÍVEL da receita (URL absoluta) quando há', () => {
    const url = 'https://abc.public.blob.vercel-storage.com/recipes/x.webp'
    const ld = buildRecipeJsonLd(baseInput({ imageUrl: url }))
    expect(ld.image).toBe(url)
  })

  it('NUNCA emite aggregateRating/estrelas (Voto ≠ nota)', () => {
    const ld = buildRecipeJsonLd(baseInput({ voteCount: 42 }))
    expect(JSON.stringify(ld)).not.toMatch(/aggregateRating|ratingValue|reviewCount/i)
    expect('aggregateRating' in ld).toBe(false)
  })

  it('author quando há dono humano (sem fonte)', () => {
    const ld = buildRecipeJsonLd(baseInput({ author: { name: 'Maria', handle: 'maria' } }))
    expect(ld.author).toEqual({ '@type': 'Person', name: 'Maria' })
  })

  it('isBasedOn/fonte quando web_imported (creditа a fonte externa, não o importador)', () => {
    const ld = buildRecipeJsonLd(
      baseInput({
        author: undefined,
        source: { url: 'https://exemplo.com/receita', name: 'Site Exemplo' },
      }),
    )
    // Atribuição à FONTE externa: nunca um author humano inventado.
    expect(ld.author).toBeUndefined()
    expect(ld.isBasedOn).toBe('https://exemplo.com/receita')
  })

  it('inLanguage acompanha o locale corrente', () => {
    const ld = buildRecipeJsonLd(baseInput({ locale: 'en-US' }))
    expect(ld.inLanguage).toBe('en-US')
  })
})

describe('serializeJsonLd — string segura pro <script> (XSS de </script>)', () => {
  it('escapa `<` para que </script> embutido no conteúdo não feche a tag', () => {
    const ld = buildRecipeJsonLd(
      baseInput({ name: 'Bolo </script><script>alert(1)</script>' }),
    )
    const s = serializeJsonLd(ld)
    expect(s).not.toContain('</script>')
    // ainda é JSON válido e preserva o dado (apenas o `<` foi escapado).
    expect(() => JSON.parse(s)).not.toThrow()
    expect(JSON.parse(s).name).toBe('Bolo </script><script>alert(1)</script>')
  })
})
